import express from "express";
import { getUser, login, logout, register, verifyaccount } from "../controllers/authController.js";
import { isAuthenticated } from "../middleware/authMiddleware.js";
const authRouter=express.Router();
authRouter.post('/register',register);
authRouter.post('/verify/:token',verifyaccount);
authRouter.post('/login',login);
authRouter.get('/logout',isAuthenticated,logout);
authRouter.get('/me',isAuthenticated,getUser);
export default authRouter;